export const OPEN_FORM = 'OPEN_FORM';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const ACTIVE_PROJECT = 'ACTIVE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';